### ISSUE TITLE
License and crediting?

### ISSUE THREAD

**Issue by rudzik8** [CasimirKaPazi/placeitem#1]
I'm working on [my personal fork of Voxelgarden on Codeberg](https://codeberg.org/rudzik8/Voxelgarden/), and I really wanted to incorporate this mod with some fixes into the next release.

However, I don't know what license applies here. I suppose it's LGPL 2.1-or-later, similar to exclusive Voxelgarden mods, but there's no README or at least LICENSE file to specify that.

Also I can see that you use custom textures here, and they don't look like they are made from scratch. It would be really nice to know what they are based on exactly.

Thanks

**Comment by CasimirKaPazi** [comment]
Added a license and credit.

It's good to see someone picking up Voxelgarden. I just don't have the time for that anymore.

**Comment by rudzik8** [comment]
> It's good to see someone picking up Voxelgarden. I just don't have the time for that anymore.

[I've finally made a release.](https://codeberg.org/rudzik8/voxelgarden/releases/tag/5.8.0). A bunch of issues fixed, mods updated and other things. There's even a trailer ready to be published!

Can you please give me Maintainer role for Voxelgarden on ContentDB? (go to Voxelgarden package -> Edit -> Maintainers) I need access to package details and releases (to change the git and publish the new release here)

**Comment by CasimirKaPazi** [comment]
I added you as maintainer.
